package com.techlogix.hirecabs.models.bookingsModels

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class BookingsStatusModel(@SerializedName("id") val id: Float,
                               @SerializedName("customerid") val customerid: Float,
                               @SerializedName("customername") val customername: String,
                               @SerializedName("triptypeid") val triptypeid: Float,
                               @SerializedName("triptypename") val triptypename: String,
                               @SerializedName("pickupcityid") val pickupcityid: Float,
                               @SerializedName("pickuplocation") val pickuplocation: String,
                               @SerializedName("pickuplatitude") val pickuplatitude: Double,
                               @SerializedName("pickuplongitude") val pickuplongitude: Double,
                               @SerializedName("dropcityid") val dropcityid: Float,
                               @SerializedName("droplocation") val droplocation: String,
                               @SerializedName("droplatitude") val droplatitude: Double,
                               @SerializedName("droplongitude") val droplongitude: Double,
                               @SerializedName("faremasterid") val faremasterid: Float,
                               @SerializedName("calculatedBaseFare") val calculatedBaseFare: Float,
                               @SerializedName("calculatedBaseKm") val calculatedBaseKm: Float,
                               @SerializedName("extraKmRate") val extraKmRate: Float,
                               @SerializedName("waitingCharges") val waitingCharges: Float,
                               @SerializedName("totalfare") val totalfare: Float,
                               @SerializedName("cgst") val cgst: Float,
                               @SerializedName("sgst") val sgst: Float,
                               @SerializedName("igst") val igst: Float,
                               @SerializedName("totalTravelledKms") val totalTravelledKms: Float,
                               @SerializedName("totalFareWithGst") val totalFareWithGst: Float,
                               @SerializedName("paymentTypeId") val paymentTypeId: Float,
                               @SerializedName("BookingAmount") val BookingAmount: Float,
                               @SerializedName("amountToBeCollected") val amountToBeCollected: Float,
                               @SerializedName("driverId") val driverId: Float,
                               @SerializedName("vehicleNumber") val vehicleNumber: String,
                               @SerializedName("promoCodeId") val promoCodeId: Float,
                               @SerializedName("discountAmount") val discountAmount: Float,
                               @SerializedName("pickupDate") val pickupDate: String,
                               @SerializedName("pickupTime") val pickupTime: String,
                               @SerializedName("riderOtp") val riderOtp: Float,
                               @SerializedName("cancelledBy") val cancelledBy: String,
                               @SerializedName("cancelledReason") val cancelledReason: String,
                               @SerializedName("bookingStatus") val bookingStatus: Float,
                               @SerializedName("bookingStatusText") val bookingStatusText: String,
                               @SerializedName("tempbookingid") val tempbookingid: Float,
                               @SerializedName("googlemapimagepath") val googlemapimagepath: String,
                               @SerializedName("vehiclecategory") val vehiclecategory: String,
                               @SerializedName("paymentmode") val paymentmode: String,
                               @SerializedName("createdAt") val createdAt: String,
                               @SerializedName("updatedAt") val updatedAt: String,
                               @SerializedName("vehicleName") val vehicleName: String,
                               @SerializedName("DriverName") val DriverName: String):Serializable {

}