package com.techlogix.pacaps.models.drviersModels

import com.google.gson.annotations.SerializedName

data class GetAllDriversResponseModel(@SerializedName("id") val id: Int,
                                      @SerializedName("name") val name: String,
                                      @SerializedName("mobile") val mobile: Int,
                                      @SerializedName("password") val password: Int,
                                      @SerializedName("vehicleno") val vehicleno: String,
                                      @SerializedName("vehiclecategoryid") val vehiclecategoryid: Int,
                                      @SerializedName("availability") val availability: Int,
                                      @SerializedName("cityid") val cityid: Int,
                                      @SerializedName("currentlat") val currentlat: Double,
                                      @SerializedName("currentlng") val currentlng: Double,
                                      @SerializedName("tracktime") val tracktime: String,
                                      @SerializedName("location") val location: String,
                                      @SerializedName("worktypeid") val worktypeid: Int,
                                      @SerializedName("triptypeid") val triptypeid: Int,
                                      @SerializedName("tokenid") val tokenid: String,
                                      @SerializedName("accountno") val accountno: Int,
                                      @SerializedName("bankname") val bankname: String,
                                      @SerializedName("nameasperbank") val nameasperbank: String,
                                      @SerializedName("ifsccode") val ifsccode: String,
                                      @SerializedName("rcno") val rcno: String,
                                      @SerializedName("rcpath") val rcpath: String,
                                      @SerializedName("rcpathback") val rcpathback: String,
                                      @SerializedName("rcexpiry") val rcexpiry: String,
                                      @SerializedName("dlno") val dlno: String,
                                      @SerializedName("dlpath") val dlpath: String,
                                      @SerializedName("dlpathback") val dlpathback: String,
                                      @SerializedName("dlexpiry") val dlexpiry: String,
                                      @SerializedName("pollutionno") val pollutionno: String,
                                      @SerializedName("pollutionpath") val pollutionpath: String,
                                      @SerializedName("pollutionexpiry") val pollutionexpiry: String,
                                      @SerializedName("insuranceno") val insuranceno: String,
                                      @SerializedName("insurancepath") val insurancepath: String,
                                      @SerializedName("insuranceexpiry") val insuranceexpiry: String,
                                      @SerializedName("fcno") val fcno: String,
                                      @SerializedName("fcpath") val fcpath: String,
                                      @SerializedName("fcexpiry") val fcexpiry: String,
                                      @SerializedName("otherdocumentno") val otherdocumentno: String,
                                      @SerializedName("otherdocumentpath") val otherdocumentpath: String,
                                      @SerializedName("otherdoucmentexpiry") val otherdoucmentexpiry: String,
                                      @SerializedName("profilepath") val profilepath: String,
                                      @SerializedName("approved") val approved: Int,
                                      @SerializedName("loggedin") val loggedin: Int,
                                      @SerializedName("lastloginstatusat") val lastloginstatusat: String,
                                      @SerializedName("createdAt") val createdAt: String,
                                      @SerializedName("updatedAt") val updatedAt: String)


